# Generated by Django 4.2.7 on 2023-12-03 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='presale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='presale_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='waiting_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
