# Generated by Django 4.2.7 on 2023-12-03 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_presale_event_presale_tickets_event_sale_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_amount', models.PositiveIntegerField(default=1)),
                ('payment_voucher', models.FileField(upload_to='comprovantes_pagamento/')),
                ('tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.ticket')),
            ],
        ),
    ]
