# Generated by Django 4.2.7 on 2023-12-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_payment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='client',
        ),
    ]
